spring.application.name=service-transaction
server.port=8484
management.endpoints.web.exposure.include=health,info

eureka.instance.instance-identification=${spring.application.name}:${server.port}

spring.config.import=optional:configserver:
spring.cloud.config.discovery.service-identification=config-server-bc

# Profile active
spring.profiles.active=local

# info eureka
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description= Transaction Service
info.app.version=1.0.0

