openapi: "3.0.1"
info:
  title: Transactions service API
  description: API to managment transaction of accounts bank
  version: 1.0.0
servers:
  - url: http://localhost:8484
    description: local server
paths:
  /api/transactions:
    get:
      summary: Getting transactions.
      operationId: findAll
      responses:
        '200':
          description: Success find all transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TransactionRS"
    post:
      summary: Create new transaction of bank.
      operationId: createTransaction
      requestBody:
        description: Details to create new transaction.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionRQ"
      responses:
        '200':
          description: Success create
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionRS"
  /api/transactions/{transactionId}:
    get:
      summary: Getting transaction by id
      operationId: getTransaction
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionRS"
        '404':
          description: Product not found
    put:
      summary: Updated transaction
      operationId: udpate
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Details to updated transacation.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRQ'
      responses:
        '200':
          description: Success updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionRS'
        '404':
          description: Transaction not found to updated

    delete:
      summary: Delete transaction
      operationId: delete
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfull deleted
        '404':
          description: Transaction not found to delete
  /api/transactions/customer/{customerId}:
    get:
      summary: Getting transaction by customerId
      operationId: getTransactionByCustomerId
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TransactionRS"
        '404':
          description: Product not found
components:
  schemas:
    TransactionRQ:
      type: object
      properties:
        customerId:
          type: string
          description: customer id
        productId:
          type: string
          description: product id
        productType:
          type: string
          description: product type
        amountMoved:
          type: number
          format: double
          description: amount to process
        amount:
          type: number
          format: double
          description: amount DEPOSIT or WITHDRAWAL without commision
        movementType:
          type: string
          description: type of movement DEPOSIT , WITHDRAWAL
        result:
          type: string
          description: indicate if transaction is success or not
        commissionAmount:
          type: number
          format: double
          description: commision amount for transaction
    TransactionRS:
      type: object
      properties:
        id:
          type: string
          description: unique transaction id
        productType:
          type: string
          description: product type
        productId:
          type: string
          description: product id
        amountMoved:
          type: number
          format: double
          description: amount of transaction
        amount:
          type: number
          format: double
          description: amount DEPOSIT or WITHDRAWAL without commision
        result:
          type: string
          description: indicate if transaction was success or not
        movementType:
          type: string
          description: type of movement DEPOSIT , WITHDRAWAL
        observation:
          type: string
          description: observations
        commissionAmount:
          type: number
          format: double
          description: commission amount for transaction
        customerId:
          type: string
          description: customer id
        dateOfTransaction:
          type: string
          format: date
